/**
 * Locality / upazila-scale flood & cyclone hotspots for hazard map.
 * Large division circles hide "where is water high" — these pin named places.
 */
export interface LocalHazardHotspot {
  zone_id: string;
  name: string;
  name_bn: string;
  hazard_type: "flood" | "cyclone";
  /** 1–5 water / wind intensity shown on map */
  risk_level: number;
  division: string;
  district: string;
  /** Upazila or urban locality label (EN) */
  locality: string;
  locality_bn: string;
  lat: number;
  lng: number;
  /** Keep small — neighborhood / upazila footprint */
  radius_km: number;
  /** Short Bangla note for tooltip (water depth / inundation character) */
  water_note_bn: string;
  water_note_en: string;
}

/** Regional corridors — kept softer / smaller so local pins remain readable */
export const REGIONAL_HAZARD_BASELINES: LocalHazardHotspot[] = [
  {
    zone_id: "cyclone-ctg-coast",
    name: "Chattogram Coastal Cyclone Belt",
    name_bn: "চট্টগ্রাম উপকূলীয় ঘূর্ণিঝড় বেল্ট",
    hazard_type: "cyclone",
    risk_level: 4,
    division: "Chattogram",
    district: "Chattogram",
    locality: "Coastal belt",
    locality_bn: "উপকূলীয় অঞ্চল",
    lat: 22.28,
    lng: 91.82,
    radius_km: 35,
    water_note_bn: "ঘূর্ণিঝড়ে ঝড়ো হাওয়া ও জলোচ্ছ্বাস ঝুঁকি",
    water_note_en: "Storm surge & high wind corridor",
  },
  {
    zone_id: "flood-barishal-coast",
    name: "Barishal Coastal Flood Plain",
    name_bn: "বরিশাল উপকূলীয় বন্যা সমভূমি",
    hazard_type: "flood",
    risk_level: 3,
    division: "Barishal",
    district: "Barishal",
    locality: "Coastal plain",
    locality_bn: "উপকূলীয় সমভূমি",
    lat: 22.7,
    lng: 90.35,
    radius_km: 30,
    water_note_bn: "জোয়ার ও বৃষ্টির পানি দীর্ঘস্থায়ী জলাবদ্ধতা",
    water_note_en: "Tidal + rainwater prolonged inundation",
  },
  {
    zone_id: "flood-sylhet-haor",
    name: "Sylhet Haor Flood Basin",
    name_bn: "সিলেট হাওর বন্যা অববাহিকা",
    hazard_type: "flood",
    risk_level: 3,
    division: "Sylhet",
    district: "Sunamganj",
    locality: "Haor basin",
    locality_bn: "হাওর অববাহিকা",
    lat: 25.0,
    lng: 91.45,
    radius_km: 28,
    water_note_bn: "হাওরে মৌসুমি পানি বৃদ্ধি",
    water_note_en: "Seasonal haor inundation",
  },
];

/** Named local flood hotspots — Chattogram + other high-signal places */
export const LOCAL_FLOOD_HOTSPOTS: LocalHazardHotspot[] = [
  // —— Chattogram city / adjacent localities (user examples) ——
  {
    zone_id: "flood-bohoddarhat",
    name: "Bohoddarhat (Bahaddarhat) Waterlogging",
    name_bn: "বহদ্দারহাট জলাবদ্ধতা",
    hazard_type: "flood",
    risk_level: 5,
    division: "Chattogram",
    district: "Chattogram",
    locality: "Bohoddarhat",
    locality_bn: "বহদ্দারহাট",
    lat: 22.3695,
    lng: 91.8428,
    radius_km: 2.2,
    water_note_bn: "এখানে অনেক পানি — রাস্তা ও নিচু এলাকায় জলাবদ্ধতা তীব্র",
    water_note_en: "Heavy standing water — roads & low pockets badly inundated",
  },
  {
    zone_id: "flood-banshkhali",
    name: "Banshkhali Coastal Flood",
    name_bn: "বাঁশখালী উপকূলীয় বন্যা",
    hazard_type: "flood",
    risk_level: 5,
    division: "Chattogram",
    district: "Chattogram",
    locality: "Banshkhali",
    locality_bn: "বাঁশখালী",
    lat: 22.215,
    lng: 91.938,
    radius_km: 6.5,
    water_note_bn: "উপকূলে প্রবল পানি উঠেছে — জলোচ্ছ্বাস ও বৃষ্টির সমন্বয়",
    water_note_en: "Coastal surge + rain — widespread inundation",
  },
  {
    zone_id: "flood-satkania",
    name: "Satkania Flood Hotspot",
    name_bn: "সাতকানিয়া বন্যা হটস্পট",
    hazard_type: "flood",
    risk_level: 5,
    division: "Chattogram",
    district: "Chattogram",
    locality: "Satkania",
    locality_bn: "সাতকানিয়া",
    lat: 22.076,
    lng: 92.049,
    radius_km: 5.5,
    water_note_bn: "সাতকানিয়ায় অনেক পানি — নদী অববাহিকায় বন্যা",
    water_note_en: "River-basin flooding — high water across Satkania",
  },
  {
    zone_id: "flood-patiya",
    name: "Patiya Lowland Flood",
    name_bn: "পটিয়া নিম্নাঞ্চল বন্যা",
    hazard_type: "flood",
    risk_level: 4,
    division: "Chattogram",
    district: "Chattogram",
    locality: "Patiya",
    locality_bn: "পটিয়া",
    lat: 22.295,
    lng: 91.98,
    radius_km: 4.5,
    water_note_bn: "নিচু এলাকায় পানি জমেছে",
    water_note_en: "Lowland waterlogging",
  },
  {
    zone_id: "flood-anwara",
    name: "Anwara Flood Pocket",
    name_bn: "আনোয়ারা বন্যা পকেট",
    hazard_type: "flood",
    risk_level: 4,
    division: "Chattogram",
    district: "Chattogram",
    locality: "Anwara",
    locality_bn: "আনোয়ারা",
    lat: 22.183,
    lng: 91.866,
    radius_km: 4.0,
    water_note_bn: "উপকূল সংলগ্ন এলাকায় পানি বৃদ্ধি",
    water_note_en: "Coastal fringe water rise",
  },
  {
    zone_id: "flood-chandgaon",
    name: "Chandgaon Waterlogging",
    name_bn: "চান্দগাঁও জলাবদ্ধতা",
    hazard_type: "flood",
    risk_level: 4,
    division: "Chattogram",
    district: "Chattogram",
    locality: "Chandgaon",
    locality_bn: "চান্দগাঁও",
    lat: 22.382,
    lng: 91.855,
    radius_km: 2.0,
    water_note_bn: "শহরের নিচু সড়কে পানি জমে",
    water_note_en: "Urban low roads waterlogged",
  },
  {
    zone_id: "flood-agrabad-karnaphuli",
    name: "Agrabad–Karnaphuli Bank Flood",
    name_bn: "আগ্রাবাদ–কর্ণফুলী তীর বন্যা",
    hazard_type: "flood",
    risk_level: 4,
    division: "Chattogram",
    district: "Chattogram",
    locality: "Agrabad",
    locality_bn: "আগ্রাবাদ",
    lat: 22.323,
    lng: 91.812,
    radius_km: 2.5,
    water_note_bn: "নদীতীরে জোয়ার ও বৃষ্টির পানি বাড়ছে",
    water_note_en: "Riverbank tide + rain surge",
  },
  {
    zone_id: "flood-halishahar",
    name: "Halishahar Waterlogging",
    name_bn: "হালিশহর জলাবদ্ধতা",
    hazard_type: "flood",
    risk_level: 3,
    division: "Chattogram",
    district: "Chattogram",
    locality: "Halishahar",
    locality_bn: "হালিশহর",
    lat: 22.336,
    lng: 91.786,
    radius_km: 2.0,
    water_note_bn: "মাঝারি জলাবদ্ধতা",
    water_note_en: "Moderate waterlogging",
  },
  {
    zone_id: "flood-sandwip",
    name: "Sandwip Island Flood & Surge",
    name_bn: "সন্দ্বীপ দ্বীপ বন্যা ও জলোচ্ছ্বাস",
    hazard_type: "flood",
    risk_level: 5,
    division: "Chattogram",
    district: "Chattogram",
    locality: "Sandwip",
    locality_bn: "সন্দ্বীপ",
    lat: 22.483,
    lng: 91.455,
    radius_km: 8.0,
    water_note_bn: "দ্বীপে জলোচ্ছ্বাস ও বৃষ্টির পানি উচ্চ ঝুঁকি",
    water_note_en: "Island surge + rain — high flood risk",
  },
  {
    zone_id: "flood-coxs-bazar-teknaf",
    name: "Cox's Bazar–Teknaf Coastal Flood",
    name_bn: "কক্সবাজার–টেকনাফ উপকূলীয় বন্যা",
    hazard_type: "flood",
    risk_level: 4,
    division: "Chattogram",
    district: "Cox's Bazar",
    locality: "Teknaf",
    locality_bn: "টেকনাফ",
    lat: 20.862,
    lng: 92.306,
    radius_km: 7.0,
    water_note_bn: "উপকূলে জলোচ্ছ্বাস ঝুঁকি",
    water_note_en: "Coastal storm-surge flood risk",
  },
  {
    zone_id: "flood-feni-town",
    name: "Feni Town Flood Pocket",
    name_bn: "ফেনী শহর বন্যা পকেট",
    hazard_type: "flood",
    risk_level: 4,
    division: "Chattogram",
    district: "Feni",
    locality: "Feni Sadar",
    locality_bn: "ফেনী সদর",
    lat: 23.016,
    lng: 91.398,
    radius_km: 4.0,
    water_note_bn: "নদী তীরবর্তী এলাকায় পানি বাড়ছে",
    water_note_en: "River-adjacent water rise",
  },
  // —— Other divisions (local granularity) ——
  {
    zone_id: "flood-companiganj-sylhet",
    name: "Companiganj Haor Flood",
    name_bn: "কোম্পানীগঞ্জ হাওর বন্যা",
    hazard_type: "flood",
    risk_level: 5,
    division: "Sylhet",
    district: "Sylhet",
    locality: "Companiganj",
    locality_bn: "কোম্পানীগঞ্জ",
    lat: 25.101,
    lng: 91.65,
    radius_km: 6.0,
    water_note_bn: "হাওরে পানি উচ্চ স্তরে",
    water_note_en: "Haor water at high stage",
  },
  {
    zone_id: "flood-gowainghat",
    name: "Gowainghat Flash Flood",
    name_bn: "গোয়াইনঘাট আকস্মিক বন্যা",
    hazard_type: "flood",
    risk_level: 4,
    division: "Sylhet",
    district: "Sylhet",
    locality: "Gowainghat",
    locality_bn: "গোয়াইনঘাট",
    lat: 25.102,
    lng: 92.228,
    radius_km: 5.0,
    water_note_bn: "পাহাড়ি ঢলে আকস্মিক পানি",
    water_note_en: "Flash flood from hills",
  },
  {
    zone_id: "flood-keraniganj",
    name: "Keraniganj Peripheral Flood",
    name_bn: "কেরাণীগঞ্জ পেরিফেরাল বন্যা",
    hazard_type: "flood",
    risk_level: 4,
    division: "Dhaka",
    district: "Dhaka",
    locality: "Keraniganj",
    locality_bn: "কেরাণীগঞ্জ",
    lat: 23.685,
    lng: 90.335,
    radius_km: 4.0,
    water_note_bn: "বুড়িগঙ্গা তীরবর্তী জলাবদ্ধতা",
    water_note_en: "Buriganga-side waterlogging",
  },
  {
    zone_id: "flood-patharghata",
    name: "Patharghata Coastal Flood",
    name_bn: "পাথরঘাটা উপকূলীয় বন্যা",
    hazard_type: "flood",
    risk_level: 5,
    division: "Barishal",
    district: "Barguna",
    locality: "Patharghata",
    locality_bn: "পাথরঘাটা",
    lat: 22.045,
    lng: 89.972,
    radius_km: 6.0,
    water_note_bn: "ঘূর্ণিঝড় ও জোয়ারের পানি উচ্চ ঝুঁকি",
    water_note_en: "Cyclone + tidal flood high risk",
  },
];

export function allStaticHazardZones(): LocalHazardHotspot[] {
  return [...LOCAL_FLOOD_HOTSPOTS, ...REGIONAL_HAZARD_BASELINES];
}
