-- Phase 2: curated thesis / expert / policy-brief abstracts (copyright-safe summaries)
-- Depends on: 11-local-entities.sql

SET client_encoding TO 'UTF8';

INSERT INTO local_evidence_items (
  id, kind, topics, title, title_bn, abstract, abstract_bn,
  author, institution, source_name, url, year, published_at, strength,
  geo_scope, district, division, solutions, entity_id, created_at, updated_at
) VALUES
(
  'e2100001-0001-4001-8001-000000000001',
  'THESIS', ARRAY['POWER']::text[],
  'Feeder-level load-shedding and evening peak in secondary cities',
  'সেকেন্ডারি শহরে ফিডার লোডশেডিং ও সন্ধ্যার পিক',
  'Abstract: evening peak on 11kV feeders, not city-wide generation, drives most urban outages. Ward offices should publish restore ETAs within 2 hours.',
  'সারসংক্ষেপ: নগর বিভ্রাটের বেশিরভাগ ১১ কেভি ফিডার পিক থেকে আসে, সিটি-ওয়াইড জেনারেশন নয়। ওয়ার্ড অফিসে ২ ঘণ্টার মধ্যে পুনরুদ্ধার সময় প্রকাশ করুন।',
  'Rahman, S.', 'BIDS', 'BIDS Working Paper (demo abstract)',
  'https://geoinsight.local/seed/evidence/bids-feeder-peak-2024',
  2024, TIMESTAMPTZ '2024-11-12 10:00:00+06', 5,
  'NATIONAL', NULL, NULL,
  '{"now":{"en":"Post feeder ETA at the ward office and cover clinic/school with a generator.","bn":"ওয়ার্ড অফিসে ফিডার ETA টানুন; ক্লিনিক/স্কুলে জেনারেটর দিন।"},"week":{"en":"Map repeat-trip feeders and rotate crew night shifts.","bn":"বারবার ট্রিপ হওয়া ফিডার ম্যাপ করুন, নাইট শিফট ঘোরান।"},"days90":{"en":"Budget capacitor banks and a public outage dashboard.","bn":"ক্যাপাসিটর ব্যাংক ও পাবলিক আউটজ ড্যাশবোর্ড বাজেট করুন।"}}'::jsonb,
  NULL, NOW(), NOW()
),
(
  'e2100001-0001-4001-8001-000000000002',
  'THESIS', ARRAY['GAS']::text[],
  'Low-pressure clusters in Chattogram Titas laterals',
  'চট্টগ্রাম তিতাস ল্যাটারালে নিম্নচাপ ক্লাস্টার',
  'Abstract: cooking-hour pressure drops concentrate in a few laterals. Isolate smell reports in 30 minutes; do not wait for a city-wide notice.',
  'সারসংক্ষেপ: রান্নার সময়ে চাপ কমে নির্দিষ্ট ল্যাটারালে। গন্ধের রিপোর্ট ৩০ মিনিটে আলাদা করুন; সিটি-ওয়াইড নোটিশের অপেক্ষা নয়।',
  'Chowdhury, N.', 'CUET', 'CUET Energy Lab (demo abstract)',
  'https://geoinsight.local/seed/evidence/cuet-titas-laterals-2023',
  2023, TIMESTAMPTZ '2023-06-20 10:00:00+06', 5,
  'DISTRICT', 'Chattogram', 'Chattogram',
  '{"now":{"en":"Isolate the smelling lane, call Titas, restrict cooking hours.","bn":"গন্ধের গলি আলাদা করুন, তিতাসকে কল দিন, রান্নার সময় সীমিত করুন।"},"week":{"en":"Pressure loggers on the three worst laterals.","bn":"সবচেয়ে খারাপ তিন ল্যাটারালে প্রেশার লগার বসান।"},"days90":{"en":"Retire leaking service pipes in the hot cluster.","bn":"হট ক্লাস্টারের লিক পাইপ বদলান।"}}'::jsonb,
  NULL, NOW(), NOW()
),
(
  'e2100001-0001-4001-8001-000000000003',
  'EXPERT', ARRAY['FUEL','UNREST']::text[],
  'Agrabad pump queues: publish hours before the crowd forms',
  'আগ্রাবাদ পাম্প লাইন: ভিড় হওয়ার আগে সময় প্রকাশ',
  'Expert column: unofficial WhatsApp times create panic queues. A same-day tanker ETA on the city page cuts wait time.',
  'বিশেষজ্ঞ কলাম: অনানুষ্ঠানিক হোয়াটসঅ্যাপ সময় আতঙ্কের লাইন তৈরি করে। সিটি পেজে আজকের ট্যাংকার ETA অপেক্ষা কমায়।',
  'Karim, F.', 'The Daily Star', 'The Daily Star op-ed (demo summary)',
  'https://geoinsight.local/seed/evidence/star-agrabad-fuel-queue-2026',
  2026, TIMESTAMPTZ '2026-08-10 09:00:00+06', 4,
  'ENTITY', 'Chattogram', 'Chattogram',
  '{"now":{"en":"Police queue control plus official pump hours on the CCC page.","bn":"পুলিশ দিয়ে লাইন নিয়ন্ত্রণ এবং সিসিসি পেজে অফিসিয়াল পাম্প সময়।"},"week":{"en":"Two overflow pumps and a tanker slot calendar.","bn":"দুই ওভারফ্লো পাম্প ও ট্যাংকার স্লট ক্যালেন্ডার।"},"days90":{"en":"Depot-to-ward allocation published weekly.","bn":"ডিপো-টু-ওয়ার্ড বরাদ্দ সাপ্তাহিক প্রকাশ।"}}'::jsonb,
  'c9000001-0001-4001-8001-000000000001', NOW(), NOW()
),
(
  'e2100001-0001-4001-8001-000000000004',
  'THESIS', ARRAY['DRAINAGE','WATER']::text[],
  'Canal outfall blockage and ward waterlogging in CCC',
  'সিসিসিতে খাল আউটফল ব্লক ও ওয়ার্ড জলাবদ্ধতা',
  'Abstract: 36-canal network fails at outfalls, not mid-reach. Pumps without outfall clearing shift water to the next ward.',
  'সারসংক্ষেপ: ৩৬ খালের ব্যর্থতা আউটফলে, মাঝপথে নয়। আউটফল না পরিষ্কার করে পাম্প চালালে পানি পাশের ওয়ার্ডে যায়।',
  'Das, R.', 'CU / IWFM', 'Urban water thesis (demo abstract)',
  'https://geoinsight.local/seed/evidence/cu-ccc-canal-outfall-2022',
  2022, TIMESTAMPTZ '2022-12-01 10:00:00+06', 5,
  'ENTITY', 'Chattogram', 'Chattogram',
  '{"now":{"en":"Standby pumps and clear the named outfall before the next rain band.","bn":"পাম্প স্ট্যান্ডবাই, পরের বৃষ্টির আগে নাম করা আউটফল পরিষ্কার।"},"week":{"en":"CCTV the three choke outfalls; publish a dredge log.","bn":"তিন চোক আউটফলে সিসিটিভি; ড্রেজ লগ প্রকাশ।"},"days90":{"en":"Retender the chronic outfall reaches with a 72-hour SLA.","bn":"ক্রনিক আউটফল রিচে ৭২ ঘণ্টা SLA দিয়ে রিটেন্ডার।"}}'::jsonb,
  'c9000001-0001-4001-8001-000000000001', NOW(), NOW()
),
(
  'e2100001-0001-4001-8001-000000000005',
  'POLICY_BRIEF', ARRAY['UNREST']::text[],
  'De-escalation windows: councillor plus police liaison in the first hour',
  'ডি-এস্কেলেশন: প্রথম ঘণ্টায় কাউন্সিলর ও পুলিশ যোগাযোগ',
  'Policy brief: named protest clusters cool when a local councillor is on site within 60 minutes and a school/hospital route stays open.',
  'পলিসি ব্রিফ: ৬০ মিনিটের মধ্যে কাউন্সিলর মাঠে থাকলে এবং স্কুল/হাসপাতাল রুট খোলা থাকলে ক্লাস্টার ঠান্ডা হয়।',
  'BIGD Governance desk', 'BIGD', 'BIGD policy note (demo abstract)',
  'https://geoinsight.local/seed/evidence/bigd-deescalation-window-2025',
  2025, TIMESTAMPTZ '2025-03-18 10:00:00+06', 4,
  'NATIONAL', NULL, NULL,
  '{"now":{"en":"Send councillor + police liaison; keep school/hospital corridor open.","bn":"কাউন্সিলর ও পুলিশ যোগাযোগ পাঠান; স্কুল/হাসপাতাল করিডোর খোলা রাখুন।"},"week":{"en":"Ward meeting room standing offer; no unannounced eviction.","bn":"ওয়ার্ড মিটিং রুম স্থায়ী অফার; ঘোষণা ছাড়া উচ্ছেদ নয়।"},"days90":{"en":"Written liaison roster for each known protest theme.","bn":"প্রতি পরিচিত আন্দোলন থিমে লিখিত যোগাযোগ রোস্টার।"}}'::jsonb,
  NULL, NOW(), NOW()
),
(
  'e2100001-0001-4001-8001-000000000006',
  'EXPERT', ARRAY['UNREST','FUEL']::text[],
  'Port corridor strikes: keep one calm lane for hospital traffic',
  'বন্দর করিডোর ধর্মঘট: হাসপাতালের জন্য একটি শান্ত লেন',
  'Expert interview: blockade harm is highest when ambulances cannot pass Agrabad–port. One negotiated lane is the first deal.',
  'বিশেষজ্ঞ সাক্ষাৎকার: অ্যাম্বুলেন্স আগ্রাবাদ–বন্দর যেতে না পারলে ক্ষতি সবচেয়ে বেশি। প্রথম চুক্তি একটি সমঝোতা লেন।',
  'Hossain, M.', 'Prothom Alo', 'Prothom Alo interview (demo summary)',
  'https://geoinsight.local/seed/evidence/pa-port-corridor-lane-2026',
  2026, TIMESTAMPTZ '2026-08-08 11:00:00+06', 4,
  'DISTRICT', 'Chattogram', 'Chattogram',
  '{"now":{"en":"Negotiate one hospital/school lane; publish it on radio.","bn":"হাসপাতাল/স্কুলের এক লেন সমঝোতা; রেডিওতে প্রকাশ।"},"week":{"en":"Standing MoU with truck associations on emergency lanes.","bn":"জরুরি লেনে ট্রাক সমিতির সাথে স্থায়ী সমঝোতা।"},"days90":{"en":"Alternate bus route cards at two chokepoints.","bn":"দুই চোকপয়েন্টে বিকল্প বাস রুট কার্ড।"}}'::jsonb,
  NULL, NOW(), NOW()
),
(
  'e2100001-0001-4001-8001-000000000007',
  'THESIS', ARRAY['UNREST','UNEMPLOYMENT']::text[],
  'Kalurghat BSCIC wage disputes and local unrest spillover',
  'কালুরঘাট বিসিক মজুরি বিরোধ ও স্থানীয় অসন্তোষ',
  'Abstract: unpaid-wage sit-ins near the bridge approach spill into traffic unrest within 6 hours unless a labour liaison is on site.',
  'সারসংক্ষেপ: সেতু অ্যাপ্রোচে বকেয়া মজুরির অবস্থান ৬ ঘণ্টার মধ্যে ট্রাফিক অসন্তোষে ছড়ায় যদি শ্রম যোগাযোগ কর্মী না থাকে।',
  'Akter, L.', 'University of Chittagong', 'Labour geography thesis (demo abstract)',
  'https://geoinsight.local/seed/evidence/cu-kalurghat-wage-2024',
  2024, TIMESTAMPTZ '2024-05-09 10:00:00+06', 4,
  'ENTITY', 'Chattogram', 'Chattogram',
  '{"now":{"en":"Ward meeting room + labour liaison; no eviction today.","bn":"ওয়ার্ড মিটিং রুম ও শ্রম যোগাযোগ; আজ উচ্ছেদ নয়।"},"week":{"en":"Named wage-desk hours at BSCIC gate.","bn":"বিসিক গেটে নামসহ মজুরি ডেস্কের সময়।"},"days90":{"en":"Joint inspection calendar with factory owners.","bn":"কারখানা মালিকদের সাথে যৌথ পরিদর্শন ক্যালেন্ডার।"}}'::jsonb,
  'c8000001-0001-4001-8001-000000000008', NOW(), NOW()
),
(
  'e2100001-0001-4001-8001-000000000008',
  'EXPERT', ARRAY['DRAINAGE','WATER']::text[],
  'Dharmasagar–Ranidighi: clear the drain before the next shower',
  'ধর্মসাগর–রানিদীঘি: পরের বৃষ্টির আগে ড্রেন পরিষ্কার',
  'Local expert: Kandirpar waterlogging is an outfall problem, not a lake-volume problem. Same-day silt lift beats a new pump.',
  'স্থানীয় বিশেষজ্ঞ: কান্দিরপাড় জলাবদ্ধতা আউটফল সমস্যা, হ্রদের আয়তন নয়। নতুন পাম্পের চেয়ে আজই পলি তোলা কাজ করে।',
  'Begum, S.', 'Cumilla press roundtable', 'Local expert note (demo summary)',
  'https://geoinsight.local/seed/evidence/cocc-dharmasagar-drain-2026',
  2026, TIMESTAMPTZ '2026-07-22 10:00:00+06', 3,
  'ENTITY', 'Cumilla', 'Chattogram',
  '{"now":{"en":"Silt lift at the named outfall; keep Town Hall lane passable.","bn":"নাম করা আউটফলে পলি তুলুন; টাউন হল লেন চলাচলযোগ্য রাখুন।"},"week":{"en":"Mark illegal dumps on the drain bank.","bn":"ড্রেন পাড়ে অবৈধ ডাম্প চিহ্নিত করুন।"},"days90":{"en":"Heritage-sensitive dredge plan for Dharmasagar edge.","bn":"ধর্মসাগর কিনারায় ঐতিহ্য-সচেতন ড্রেজ পরিকল্পনা।"}}'::jsonb,
  'c9000001-0001-4001-8001-000000000002', NOW(), NOW()
),
(
  'e2100001-0001-4001-8001-000000000009',
  'THESIS', ARRAY['CRIME']::text[],
  'Street robbery peaks after dusk on poorly lit market lanes',
  'বাজার গলিতে সন্ধ্যার পর ছিনতাই পিক',
  'Abstract: theft and snatch incidents cluster 18:00–21:00 on dark market approaches. Lighting plus a two-person patrol beats CCTV-only.',
  'সারসংক্ষেপ: চুরি/ছিনতাই ১৮:০০–২১:০০ অন্ধকার বাজার অ্যাপ্রোচে জমা হয়। শুধু সিসিটিভির চেয়ে আলো + দুইজনের টহল ভালো।',
  'Islam, T.', 'Police Staff College / CU', 'Urban crime thesis (demo abstract)',
  'https://geoinsight.local/seed/evidence/cu-dusk-snatch-lighting-2023',
  2023, TIMESTAMPTZ '2023-09-14 10:00:00+06', 4,
  'NATIONAL', NULL, NULL,
  '{"now":{"en":"Fix the three darkest market approaches tonight.","bn":"আজ রাতে তিনটি অন্ধকার বাজার অ্যাপ্রোচ ঠিক করুন।"},"week":{"en":"Two-person dusk patrol on those lanes.","bn":"সেই গলিতে সন্ধ্যায় দুইজনের টহল।"},"days90":{"en":"Sensor streetlights with a public outage ticket.","bn":"সেন্সর স্ট্রিটলাইট ও পাবলিক আউটজ টিকিট।"}}'::jsonb,
  NULL, NOW(), NOW()
),
(
  'e2100001-0001-4001-8001-000000000010',
  'POLICY_BRIEF', ARRAY['CORRUPTION']::text[],
  'Holding-tax leakage: freeze the disputed counter the same day',
  'হোল্ডিং ট্যাক্স ফাঁকি: বিতর্কিত কাউন্টার আজই স্থগিত',
  'Policy brief: citizen bribe reports drop when the named counter is frozen within 24 hours and a receipt audit is posted.',
  'পলিসি ব্রিফ: নাম করা কাউন্টার ২৪ ঘণ্টায় স্থগিত এবং রসিদ অডিট প্রকাশ করলে ঘুষের অভিযোগ কমে।',
  'BRAC Institute of Governance', 'BIGD / BRAC', 'Procurement integrity brief (demo abstract)',
  'https://geoinsight.local/seed/evidence/bigd-holding-tax-counter-2025',
  2025, TIMESTAMPTZ '2025-01-30 10:00:00+06', 4,
  'NATIONAL', NULL, NULL,
  '{"now":{"en":"Freeze the disputed counter; publish a same-day citizen note.","bn":"বিতর্কিত কাউন্টার স্থগিত; আজই নাগরিক নোট দিন।"},"week":{"en":"Receipt sample audit of the last 30 days.","bn":"গত ৩০ দিনের রসিদ নমুনা অডিট।"},"days90":{"en":"E-payment default for holding tax at that ward.","bn":"সেই ওয়ার্ডে হোল্ডিং ট্যাক্সে ই-পেমেন্ট ডিফল্ট।"}}'::jsonb,
  NULL, NOW(), NOW()
),
(
  'e2100001-0001-4001-8001-000000000011',
  'THESIS', ARRAY['EDUCATION']::text[],
  'Secondary dropout after repeated evening blackouts',
  'বারবার সন্ধ্যার বিভ্রাটের পর মাধ্যমিক ড্রপআউট',
  'Abstract: girls dropout risk rises where evening study hours are dark more than eight nights a month. School generator cover is a stopgap; feeder reliability is the fix.',
  'সারসংক্ষেপ: মাসে আট রাতের বেশি সন্ধ্যা অন্ধকার থাকলে মেয়েদের ড্রপআউট বাড়ে। স্কুল জেনারেটর সাময়িক; ফিডার নির্ভরযোগ্যতাই সমাধান।',
  'Sultana, N.', 'BRAC IED', 'Education access thesis (demo abstract)',
  'https://geoinsight.local/seed/evidence/brac-ied-blackout-dropout-2024',
  2024, TIMESTAMPTZ '2024-08-21 10:00:00+06', 4,
  'NATIONAL', NULL, NULL,
  '{"now":{"en":"Generator cover for exam-week evening classes.","bn":"পরীক্ষা সপ্তাহের সন্ধ্যার ক্লাসে জেনারেটর।"},"week":{"en":"List schools on the worst feeders.","bn":"সবচেয়ে খারাপ ফিডারের স্কুল তালিকা।"},"days90":{"en":"Joint PDB-education feeder priority for school clusters.","bn":"স্কুল ক্লাস্টারে পিডিবি-শিক্ষা যৌথ ফিডার অগ্রাধিকার।"}}'::jsonb,
  NULL, NOW(), NOW()
),
(
  'e2100001-0001-4001-8001-000000000012',
  'EXPERT', ARRAY['HEALTH']::text[],
  'Dengue ward clusters follow blocked drains, not hospital beds',
  'ডেঙ্গু ওয়ার্ড ক্লাস্টার ব্লক ড্রেন অনুসরণ করে, বেড নয়',
  'Expert: extra beds help the last mile; the first mile is larvae in clogged drains. Ward fogging without drain work returns in 10 days.',
  'বিশেষজ্ঞ: বাড়তি বেড শেষ মাইল; প্রথম মাইল ব্লক ড্রেনের লার্ভা। ড্রেন কাজ ছাড়া ফগিং ১০ দিনে ফিরে আসে।',
  'Dr. Alam, K.', 'CMCH / public health column', 'Health op-ed (demo summary)',
  'https://geoinsight.local/seed/evidence/cmch-dengue-drain-2026',
  2026, TIMESTAMPTZ '2026-06-15 10:00:00+06', 4,
  'DISTRICT', 'Chattogram', 'Chattogram',
  '{"now":{"en":"Larvicide plus drain clear on the two hottest wards.","bn":"দুই হট ওয়ার্ডে লার্ভিসাইড ও ড্রেন পরিষ্কার।"},"week":{"en":"Clinic bed buffer and a public fever desk.","bn":"ক্লিনিক বেড বাফার ও পাবলিক জ্বর ডেস্ক।"},"days90":{"en":"Ward dengue score on the mayor dashboard.","bn":"মেয়র ড্যাশবোর্ডে ওয়ার্ড ডেঙ্গু স্কোর।"}}'::jsonb,
  NULL, NOW(), NOW()
),
(
  'e2100001-0001-4001-8001-000000000013',
  'POLICY_BRIEF', ARRAY['UNEMPLOYMENT']::text[],
  'Job-fair mismatch: skills on the flyer, vacancies in EPZ',
  'জব ফেয়ার মিসম্যাচ: ফ্লায়ারে স্কিল, শূন্যপদ ইপিজেডে',
  'Policy note: ward job fairs underperform unless EPZ/BSCIC vacancies are listed the same week and transport is arranged.',
  'পলিসি নোট: একই সপ্তাহে ইপিজেড/বিসিক শূন্যপদ না থাকলে এবং যাতায়াত ব্যবস্থা না থাকলে ওয়ার্ড জব ফেয়ার কাজে লাগে না।',
  'NSDA / BIDS labour desk', 'BIDS', 'Employment brief (demo abstract)',
  'https://geoinsight.local/seed/evidence/bids-jobfair-epz-2025',
  2025, TIMESTAMPTZ '2025-09-04 10:00:00+06', 3,
  'DISTRICT', 'Chattogram', 'Chattogram',
  '{"now":{"en":"Publish this weeks EPZ/BSCIC vacancies at the ward office.","bn":"ওয়ার্ড অফিসে এই সপ্তাহের ইপিজেড/বিসিক শূন্যপদ টানুন।"},"week":{"en":"One bus to the fair from two high-unemployment wards.","bn":"দুই উচ্চ-বেকার ওয়ার্ড থেকে ফেয়ারে একটি বাস।"},"days90":{"en":"Quarterly skills calendar co-signed by factory owners.","bn":"কারখানা মালিকদের সহ-স্বাক্ষরে ত্রৈমাসিক স্কিল ক্যালেন্ডার।"}}'::jsonb,
  NULL, NOW(), NOW()
)
ON CONFLICT (url) DO UPDATE SET
  kind = EXCLUDED.kind,
  topics = EXCLUDED.topics,
  title = EXCLUDED.title,
  title_bn = EXCLUDED.title_bn,
  abstract = EXCLUDED.abstract,
  abstract_bn = EXCLUDED.abstract_bn,
  author = EXCLUDED.author,
  institution = EXCLUDED.institution,
  source_name = EXCLUDED.source_name,
  year = EXCLUDED.year,
  strength = EXCLUDED.strength,
  geo_scope = EXCLUDED.geo_scope,
  district = EXCLUDED.district,
  division = EXCLUDED.division,
  solutions = EXCLUDED.solutions,
  entity_id = EXCLUDED.entity_id,
  updated_at = NOW();
